import subprocess
import logging
from pathlib import Path
from datetime import datetime
from typing import List, Dict, Optional
import json
import random
import string

logger = logging.getLogger(__name__)


class CollaboratorManager:
    """Manages multi-collaborator commits on the same branch"""

    def __init__(self, config, repo_path="."):
        self.config = config
        self.repo_path = Path(repo_path).resolve()
        self.collaborators = config.config.get("collaborators", [])

    def _run_git(self, args: List[str]) -> str:
        """Run git command"""
        result = subprocess.run(
            ["git"] + args,
            cwd=self.repo_path,
            capture_output=True,
            text=True,
            shell=True
        )
        if result.returncode != 0:
            raise RuntimeError(result.stderr.strip())
        return result.stdout.strip()

    def setup_collaborator_identity(self, collaborator: Dict):
        """Temporarily set git identity for a collaborator"""
        self._run_git(["config", "user.name", collaborator['name']])
        self._run_git(["config", "user.email", collaborator['email']])
        logger.info(f"🔄 Switched to collaborator: {collaborator['name']} ({collaborator['email']})")

    def reset_identity(self, original_name: str, original_email: str):
        """Reset git identity to original user"""
        self._run_git(["config", "user.name", original_name])
        self._run_git(["config", "user.email", original_email])
        logger.info("🔄 Reset to original git identity")

    def create_collaborator_commit(self, branch: str, collaborator: Dict, file_index: int):
        """
        Create a commit as a specific collaborator
        
        Args:
            branch: Branch name
            collaborator: Collaborator dict with name and email
            file_index: Index to determine which file to modify
        """
        # Switch to branch
        self._run_git(["checkout", branch])
        
        # Save original identity
        original_name = self._run_git(["config", "user.name"])
        original_email = self._run_git(["config", "user.email"])
        
        try:
            # Switch to collaborator identity
            self.setup_collaborator_identity(collaborator)
            
            # Create a unique file for this collaborator
            safe_name = collaborator['name'].replace(' ', '-').lower()
            filename = f"contributions/{safe_name}-contribution-{file_index}.md"
            filepath = self.repo_path / filename
            filepath.parent.mkdir(parents=True, exist_ok=True)
            
            # Write collaborator's contribution
            timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            content = f"""# 🤝 Contribution by @{collaborator['name']}

## 📋 Contribution Details
- **Date:** {timestamp}
- **Branch:** `{branch}`
- **Contribution #:** {file_index}
- **GitHub:** [{collaborator['name']}](https://github.com/{collaborator['name']})

## 📝 Changes Made
- Added this contribution file as part of collaborative work
- Working together with team on feature development
- Multiple contributors on the same branch

## 🔍 Files Modified
- `{filename}` - Personal contribution file
- Additional changes to shared files

---
*This commit was authored by @{collaborator['name']}*
*🤖 Generated by Auto PR Creator*
"""
            filepath.write_text(content, encoding="utf-8")
            
            # Also modify a shared file to show collaboration
            readme_path = self.repo_path / "README.md"
            if readme_path.exists():
                with open(readme_path, "a", encoding="utf-8", newline="\n") as f:
                    f.write(f"\n- 🚀 Contribution from @{collaborator['name']} on {timestamp}\n")
            
            # Stage files
            self._run_git(["add", filename])
            self._run_git(["add", "README.md"])
            
            # Create commit message with co-authors
            commit_msg = f"""feat: contribution from @{collaborator['name']} (#{file_index})

This commit adds contribution from @{collaborator['name']} as part of collaborative development.

## Changes
- Added personal contribution file
- Updated README with contribution entry

Co-authored-by: {collaborator['name']} <{collaborator['email']}>
"""
            # Use temp file for commit message to handle special characters
            msg_file = self.repo_path / ".git" / "COMMIT_EDITMSG.tmp"
            msg_file.write_text(commit_msg, encoding="utf-8")
            self._run_git(["commit", "-F", str(msg_file)])
            msg_file.unlink()
            
            logger.info(f"✅ Commit created by @{collaborator['name']} (file: {filename})")
            
        finally:
            # Always reset identity
            self.reset_identity(original_name, original_email)
            
        return filename

    def create_multi_collaborator_commits(self, branch: str, num_commits_per_collaborator: int = 2):
        """
        Create multiple commits from different collaborators
        
        Args:
            branch: Branch name
            num_commits_per_collaborator: Number of commits per collaborator
        """
        all_commits = []
        
        # Create contributions directory
        contrib_dir = self.repo_path / "contributions"
        contrib_dir.mkdir(exist_ok=True)
        
        for i in range(num_commits_per_collaborator):
            for collaborator in self.collaborators:
                try:
                    filename = self.create_collaborator_commit(branch, collaborator, i+1)
                    all_commits.append({
                        'collaborator': collaborator['name'],
                        'email': collaborator['email'],
                        'file': filename,
                        'index': i+1,
                        'timestamp': datetime.now().isoformat()
                    })
                    logger.info(f"📝 Created commit #{i+1} for @{collaborator['name']}")
                except Exception as e:
                    logger.error(f"❌ Failed to create commit for {collaborator['name']}: {e}")
        
        # Create a summary file
        self._create_contributions_summary(branch, all_commits)
        
        return all_commits
    
    def _create_contributions_summary(self, branch: str, commits: List[Dict]):
        """Create a summary of all contributions"""
        summary_file = self.repo_path / "contributions" / "SUMMARY.md"
        
        content = f"""# 📊 Collaborative Contributions Summary

## 🌿 Branch: `{branch}`
**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## 👥 Contributors ({len(set(c['collaborator'] for c in commits))})

| # | Contributor | Email | Commits |
|---|-------------|-------|---------|
"""
        
        # Group by collaborator
        contributors = {}
        for commit in commits:
            if commit['collaborator'] not in contributors:
                contributors[commit['collaborator']] = {
                    'email': commit['email'],
                    'count': 0
                }
            contributors[commit['collaborator']]['count'] += 1
        
        for i, (name, data) in enumerate(contributors.items(), 1):
            content += f"| {i} | @{name} | `{data['email']}` | {data['count']} |\n"
        
        content += """
## 📝 Individual Contributions

"""
        for commit in commits:
            content += f"- [{commit['timestamp'][:10]}] @{commit['collaborator']}: `{commit['file']}`\n"
        
        content += """
---
*🤖 Generated by Auto PR Creator - Collaborative Mode*
"""
        
        summary_file.write_text(content, encoding="utf-8")
        self._run_git(["add", "contributions/SUMMARY.md"])
        
        # Commit summary as a special collaborator
        original_name = self._run_git(["config", "user.name"])
        original_email = self._run_git(["config", "user.email"])
        
        try:
            commit_msg = f"""docs: add contributions summary for {branch}

This summary tracks all collaborative contributions on this branch.

Co-authored-by: {self.config.get_coauthor_config()['name']} <{self.config.get_coauthor_config()['email']}>
"""
            msg_file = self.repo_path / ".git" / "COMMIT_EDITMSG.tmp"
            msg_file.write_text(commit_msg, encoding="utf-8")
            self._run_git(["commit", "-F", str(msg_file)])
            msg_file.unlink()
            logger.info("📊 Created contributions summary")
        finally:
            self.reset_identity(original_name, original_email)